// oapi_extensions reads an OpenAPI spec file, extracts the path component shared
// by all servers entries, validates consistency, and writes a Go source file
// containing a BasePath constant and a RegisterRoutes helper that wires a
// StrictServerInterface implementation onto an http.ServeMux.
//
// Usage:
//
//	oapi_extensions <spec.yaml> <output.go>
//
// The package name is derived from the parent directory of <output.go>.
package main

import (
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "oapi_extensions: %v\n", err)
		os.Exit(1)
	}
}

type openAPISpec struct {
	Servers []struct {
		URL string `yaml:"url"`
	} `yaml:"servers"`
}

func run() error {
	if len(os.Args) != 3 {
		return fmt.Errorf("usage: oapi_extensions <spec.yaml> <output.go>")
	}

	specFile := os.Args[1]
	outputFile := os.Args[2]

	data, err := os.ReadFile(filepath.Clean(specFile)) //nolint:gosec // CLI tool: path is a user-supplied argument
	if err != nil {
		return fmt.Errorf("read %s: %w", specFile, err)
	}

	var spec openAPISpec
	if err := yaml.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("parse %s: %w", specFile, err)
	}

	basePath, err := extractBasePath(specFile, spec)
	if err != nil {
		return err
	}

	pkg := filepath.Base(filepath.Dir(outputFile))
	if pkg == "." || pkg == "/" {
		return fmt.Errorf("output file must be inside a named package directory (got %q)", outputFile)
	}

	content := fmt.Sprintf(`// Code generated by oapi_extensions; DO NOT EDIT.

package %s

import (
	"net/http"

	"github.com/raphoester/movie-reservation-system/internal/shared/xhttpsrv"
)

// BasePath is the URL path prefix shared by all servers in the OpenAPI spec.
const BasePath = %q

// RegisterRoutes registers all spec-defined routes on mux at BasePath.
func RegisterRoutes(si StrictServerInterface, mux *http.ServeMux) {
	HandlerFromMuxWithBaseURL(NewStrictHandlerWithOptions(si, nil, StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			xhttpsrv.SetRequestError(r.Context(), err)
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			xhttpsrv.SetRequestError(r.Context(), err)
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}), mux, BasePath)
}
`, pkg, basePath)

	if err := os.WriteFile(outputFile, []byte(content), 0o600); err != nil { //nolint:gosec // CLI tool: path is a user-supplied argument
		return fmt.Errorf("write %s: %w", outputFile, err)
	}

	return nil
}

func extractBasePath(specFile string, spec openAPISpec) (string, error) {
	if len(spec.Servers) == 0 {
		return "", fmt.Errorf("%s: no servers entries found — add a servers block with the intended base path (e.g. /v1)", specFile)
	}

	paths := make([]string, 0, len(spec.Servers))
	for _, s := range spec.Servers {
		u, err := url.Parse(s.URL)
		if err != nil {
			return "", fmt.Errorf("%s: parse server URL %q: %w", specFile, s.URL, err)
		}
		paths = append(paths, strings.TrimRight(u.Path, "/"))
	}

	first := paths[0]
	for i, p := range paths[1:] {
		if p != first {
			return "", fmt.Errorf(
				"%s: servers have inconsistent base paths: server[0]=%q, server[%d]=%q",
				specFile, first, i+1, p,
			)
		}
	}

	return first, nil
}
