package main

import (
	"bytes"
	"embed"
	"errors"
	"flag"
	"fmt"
	iofs "io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"

	"github.com/samber/lo"
)

var (
	path        = flag.String("path", "", "repository path")
	context     = flag.String("context", "", "context path (required); may be nested, e.g. reservations/seating")
	featureName = flag.String("feature", "", "feature name — adds a prefix: internal/{context}/cmd/{feature}_{type}/")
	serviceType = flag.String("type", "", "type (required, must be one of: http_api, grpc_api, worker, job)")
)

func main() {
	flag.Parse()

	if err := run(); err != nil {
		if errors.Is(err, ErrInvalidParams) {
			flag.Usage()
			return
		}
		fmt.Println("genservice failed:", err)
	}
}

var ErrInvalidParams = errors.New("invalid parameters")

func parseServiceType(s string) (serviceTypeEnum, error) {
	switch s {
	case string(ServiceTypeHTTPAPI):
		return ServiceTypeHTTPAPI, nil
	case string(ServiceTypeGRPCAPI):
		return ServiceTypeGRPCAPI, nil
	case string(ServiceTypeWorker):
		return ServiceTypeWorker, nil
	case string(ServiceTypeJob):
		return ServiceTypeJob, nil
	default:
		return "", fmt.Errorf("unknown service type %q", s)
	}
}

func run() error {
	if *path == "" || *context == "" || *serviceType == "" {
		return ErrInvalidParams
	}

	if err := os.Chdir(*path); err != nil {
		return fmt.Errorf("failed to change directory to configured path %q: %w", *path, err)
	}

	parsedServiceType, err := parseServiceType(*serviceType)
	if err != nil {
		return fmt.Errorf("invalid service type %q: %w", *serviceType, err)
	}

	contextKey := strings.ReplaceAll(*context, "/", "_")

	var relativeCmdPath, serviceName string
	if *featureName != "" {
		relativeCmdPath = filepath.Join("internal", *context, "cmd", fmt.Sprintf("%s_%s", *featureName, *serviceType))
		serviceName = fmt.Sprintf("%s_%s_%s", contextKey, *featureName, *serviceType)
	} else {
		relativeCmdPath = filepath.Join("internal", *context, "cmd", *serviceType)
		serviceName = fmt.Sprintf("%s_%s", contextKey, *serviceType)
	}
	var localPort int
	if parsedServiceType != ServiceTypeJob {
		localPort = resolveLocalPort(parsedServiceType)
	}
	p := params{
		Header:          "Code initially generated by `make genservice`; EDIT AT WILL.",
		ServiceName:     serviceName,
		RelativeCmdPath: relativeCmdPath,
		LocalPort:       localPort,
	}

	bindings := map[serviceTypeEnum][]struct {
		tpl    *template.Template
		writer writer
	}{
		ServiceTypeHTTPAPI: {
			{tpl("http_api/main.go"), renderTo(filepath.Join(relativeCmdPath, "main.go"))},
			{tpl("http_api/config.go"), renderTo(filepath.Join(relativeCmdPath, "config.go"))},
			{tpl("http_api/Dockerfile.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "Dockerfile"))},
			{tpl("http_api/config/prod.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/prod.yaml"))},
			{tpl("http_api/config/staging.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/staging.yaml"))},
			{tpl("http_api/config/dev.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/dev.yaml"))},
			{tpl("http_api/config/local.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/local.yaml"))},
			{tpl("http_api/config/docker.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/docker.yaml"))},
		},
		ServiceTypeGRPCAPI: {
			{tpl("grpc_api/main.go"), renderTo(filepath.Join(relativeCmdPath, "main.go"))},
			{tpl("grpc_api/config.go"), renderTo(filepath.Join(relativeCmdPath, "config.go"))},
			{tpl("grpc_api/Dockerfile.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "Dockerfile"))},
			{tpl("grpc_api/config/prod.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/prod.yaml"))},
			{tpl("grpc_api/config/staging.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/staging.yaml"))},
			{tpl("grpc_api/config/dev.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/dev.yaml"))},
			{tpl("grpc_api/config/local.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/local.yaml"))},
			{tpl("grpc_api/config/docker.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/docker.yaml"))},
		},
		ServiceTypeWorker: {
			{tpl("worker/main.go"), renderTo(filepath.Join(relativeCmdPath, "main.go"))},
			{tpl("worker/config.go"), renderTo(filepath.Join(relativeCmdPath, "config.go"))},
			{tpl("worker/Dockerfile.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "Dockerfile"))},
			{tpl("worker/config/prod.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/prod.yaml"))},
			{tpl("worker/config/staging.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/staging.yaml"))},
			{tpl("worker/config/dev.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/dev.yaml"))},
			{tpl("worker/config/local.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/local.yaml"))},
			{tpl("worker/config/docker.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/docker.yaml"))},
		},
		ServiceTypeJob: {
			{tpl("job/main.go"), renderTo(filepath.Join(relativeCmdPath, "main.go"))},
			{tpl("job/config.go"), renderTo(filepath.Join(relativeCmdPath, "config.go"))},
			{tpl("job/Dockerfile.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "Dockerfile"))},
			{tpl("job/config/prod.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/prod.yaml"))},
			{tpl("job/config/staging.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/staging.yaml"))},
			{tpl("job/config/dev.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/dev.yaml"))},
			{tpl("job/config/local.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/local.yaml"))},
			{tpl("job/config/docker.yaml.go.tmpl"), renderTo(filepath.Join(relativeCmdPath, "configs/docker.yaml"))},
		},
	}

	wd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	for _, f := range bindings[parsedServiceType] {
		if err := f.writer(p, wd, f.tpl); err != nil {
			return fmt.Errorf("failed to write template: %w", err)
		}
	}

	return nil
}

//go:embed templates
var fileSystem embed.FS
var fs = lo.Must(iofs.Sub(fileSystem, "templates"))

func tpl(file string) *template.Template {
	return template.Must(template.New(filepath.Base(file)).ParseFS(fs, file))
}

type params struct {
	Header          string
	RelativeCmdPath string
	ServiceName     string
	LocalPort       int
}

func (p *params) resolve(wd, path string) string {
	var b bytes.Buffer
	lo.Must0(lo.Must(template.New("").Parse(path)).Execute(&b, p))
	return filepath.Join(wd, b.String())
}

func renderTo(path string) writer {
	return func(p params, wd string, tpl *template.Template) error {
		dirPath := p.resolve(wd, path)
		if err := os.MkdirAll(filepath.Dir(dirPath), 0o755); err != nil {
			return fmt.Errorf("failed to create directory: %w", err)
		}
		return writeTemplate(tpl, p, dirPath)
	}
}

func writeTemplate(t *template.Template, p params, file string) error {
	fmt.Printf("writing %s\n", file)
	var buf bytes.Buffer
	if err := t.Execute(&buf, p); err != nil {
		return fmt.Errorf("executing template; %w", err)
	}

	if err := os.WriteFile(file, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("writing file; %w", err)
	}

	return nil
}

type writer func(p params, wd string, tpl *template.Template) error

type serviceTypeEnum string

const (
	ServiceTypeHTTPAPI serviceTypeEnum = "http_api"
	ServiceTypeGRPCAPI serviceTypeEnum = "grpc_api"
	ServiceTypeWorker  serviceTypeEnum = "worker"
	ServiceTypeJob     serviceTypeEnum = "job"
)

// resolveLocalPort finds the lowest available port for the given service type
// by scanning all existing local.yaml config files.
func resolveLocalPort(serviceType serviceTypeEnum) int {
	usedPorts := collectUsedLocalPorts()

	startPort := 3000
	if serviceType == ServiceTypeGRPCAPI {
		startPort = 50051
	}

	for port := startPort; ; port++ {
		if !usedPorts[port] {
			return port
		}
	}
}

func collectUsedLocalPorts() map[int]bool {
	used := map[int]bool{}
	patterns := []string{
		filepath.Join("internal", "*", "cmd", "*", "configs", "local.yaml"),
		filepath.Join("internal", "*", "*", "cmd", "*", "configs", "local.yaml"),
	}
	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			continue
		}
		for _, match := range matches {
			if port := extractServerPort(match); port > 0 {
				used[port] = true
			}
		}
	}
	return used
}

// extractServerPort reads a service config file and extracts the server.port value
// using a simple line scan (avoids YAML anchor resolution issues).
func extractServerPort(filename string) int {
	data, err := os.ReadFile(filename)
	if err != nil {
		return 0
	}
	lines := strings.Split(string(data), "\n")
	inServer := false
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "server:" {
			inServer = true
			continue
		}
		if inServer {
			// A non-indented non-empty line means we've left the server block.
			if line != "" && line[0] != ' ' && line[0] != '\t' {
				break
			}
			if portVal, ok := strings.CutPrefix(trimmed, "port:"); ok {
				port, err := strconv.Atoi(strings.TrimSpace(portVal))
				if err == nil {
					return port
				}
			}
		}
	}
	return 0
}
