// Code initially generated by `make genservice`; EDIT AT WILL.

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/raphoester/movie-reservation-system/internal/shared/xbootstrap"
	"github.com/raphoester/movie-reservation-system/internal/shared/xlog"
)

func main() {
	if err := runServer(); err != nil {
		xlog.QuickNew().Error("failed to run service", "error", err)
		os.Exit(1)
	}
}

func runServer() error {
	if err := xbootstrap.GrpcServer(
		&Config{},
		func(ctx context.Context, props xbootstrap.GrpcDiSequenceProps[*Config]) error {
			// TODO: Build your server here
			_ = ctx
			_ = props
			return nil
		},
	); err != nil {
		return fmt.Errorf("failed to run gRPC server: %w", err)
	}

	return nil
}
